name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v3

      # setup python env
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # install python dependencies
      - name: Install Vercel CLI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # install vercel CLI via curl
      - name: Install Vercel CLI
        run: curl -fsSL https://vercel.com/download | sh

      # pull Vercel env information
      - name: Pull Vercel Env Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Build project Artifacts
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy Project Artifacts
      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token={{ secrets.VERCEL_TOKEN }}